#!/usr/bin/env python3
"""
Generate the table of AWS operations that accept an idempotency (client) token.

Input : a checkout of aws/aws-sdk-go-v2, path to codegen/sdk-codegen/aws-models
Output: JSON on stdout with two lists:
  traited  - operations whose input member carries smithy.api#idempotencyToken
             (aws-sdk-go-v2 auto-fills these with a random UUID when empty)
  untraited- operations whose input has a member *named* like a client token
             but without the trait (SDK does NOT auto-fill; must be set manually)

Usage:
  python3 gen.py /path/to/aws-models --provider-dir=/path/to/terraform-provider-aws > ops.json
  python3 gen.py /path/to/aws-models --go | gofmt > internal/idempotency/zz_ops_gen.go
  python3 gen.py /path/to/aws-models --markdown --provider-dir=/path/to/terraform-provider-aws > docs/SUPPORTED_APIS.md
"""
import json, os, re, sys

TOKEN_NAME_RE = re.compile(
    r"^(client(Request)?Token(Id)?|idempotency(Token|Key)|clientReferenceToken|requestToken|clientRequestId|callerReference|creationToken|creatorRequestId|provisionToken)$",
    re.IGNORECASE,
)

def shape_name(shape_id: str) -> str:
    return shape_id.split("#", 1)[1] if "#" in shape_id else shape_id

def mark_provider_usage(provider_dir, rows):
    """Flag rows whose operation is invoked as `.<Operation>(ctx` in any non-test
    Go file of terraform-provider-aws that imports aws-sdk-go-v2/service/<pkg>."""
    by_pkg = {}
    imp_re = re.compile(r'"github.com/aws/aws-sdk-go-v2/service/([a-z0-9]+)"')
    for root, _, files in os.walk(os.path.join(provider_dir, "internal")):
        for f in files:
            if not f.endswith(".go") or f.endswith("_test.go"):
                continue
            with open(os.path.join(root, f), errors="ignore") as fh:
                src = fh.read()
            for pkg in set(imp_re.findall(src)):
                by_pkg.setdefault(pkg, []).append(src)
    joined = {k: "\n".join(v) for k, v in by_pkg.items()}
    for r in rows:
        src = joined.get(r["go_package"], "")
        r["used_by_provider"] = bool(re.search(r"\." + re.escape(r["operation"]) + r"\(ctx\b", src))

def is_read_only(op_shape):
    return "smithy.api#readonly" in op_shape.get("traits", {})


def go_field(member):
    return member[0].upper() + member[1:]


SAMPLE_UUID = "3f2b8c1e-9a4d-5e7f-8b6c-1d2e3f4a5b6c"
SAMPLE_HEX32 = "3f2b8c1e9a4d5e7f8b6c1d2e3f4a5b6c"
SAMPLE_HEX64 = SAMPLE_HEX32 * 2


def pick_format(row):
    """Pick the first deterministic token format that satisfies the member's
    Smithy length and pattern constraints. Smithy patterns are ECMA-262; Python
    re is close enough for the character classes AWS uses. Returns None when no
    candidate fits, which the Go table marks as unsupported."""
    for name, sample in (("FormatUUID", SAMPLE_UUID), ("FormatHex32", SAMPLE_HEX32), ("FormatHex64", SAMPLE_HEX64)):
        if row["min_len"] is not None and len(sample) < row["min_len"]:
            continue
        if row["max_len"] is not None and len(sample) > row["max_len"]:
            continue
        pat = row["pattern"]
        if pat and "\\p{" not in pat:  # Unicode property classes: trust length only
            try:
                if not re.search(pat, sample):
                    continue
            except re.error:
                pass  # unparseable in Python; trust the length check
        return name
    return None


def emit_go(traited, untraited):
    rows = [(r, True) for r in traited] + [(r, False) for r in untraited]
    rows.sort(key=lambda x: (x[0]["go_package"], x[0]["operation"], x[0]["member"]))
    print("// Code generated by tools/gen-idempotent-ops/gen.py; DO NOT EDIT.")
    print()
    print("package idempotency")
    print()
    print("// opTable maps an SDK input type (\"<import path>.<Operation>Input\") to its")
    print("// idempotency token member. Lookup is one map read per API call.")
    print("var opTable = map[string]opSpec{")
    seen = set()
    for r, sdk_fills in rows:
        key = f"github.com/aws/aws-sdk-go-v2/service/{r['go_package']}.{r['operation']}Input"
        if key in seen:
            continue  # an input with two token members keeps the first; flagged in docs
        seen.add(key)
        fmt_ = pick_format(r) or "FormatUnsupported"
        print(f'\t"{key}": {{Field: "{go_field(r["member"])}", Format: {fmt_}, SDKAutoFill: {str(sdk_fills).lower()}, NameIsToken: {str(bool(TOKEN_NAME_RE.match(r["member"]))).lower()}, UsedByProvider: {str(bool(r.get("used_by_provider"))).lower()}}},')
    print("}")


def load(path):
    with open(path) as f:
        return json.load(f)

def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    md = "--markdown" in sys.argv
    models_dir = args[0]
    traited, untraited = [], []
    for fn in sorted(os.listdir(models_dir)):
        if not fn.endswith(".json"):
            continue
        model = load(os.path.join(models_dir, fn))
        shapes = model.get("shapes", {})
        service = next((s for s in shapes.values() if s.get("type") == "service"), None)
        if not service:
            continue
        svc_traits = service.get("traits", {})
        sdk_id = svc_traits.get("aws.api#service", {}).get("sdkId", fn[:-5])
        go_pkg = re.sub(r"[^a-z0-9]", "", sdk_id.lower())
        for sid, shape in shapes.items():
            if shape.get("type") != "operation":
                continue
            inp = shape.get("input", {}).get("target")
            if not inp or inp == "smithy.api#Unit":
                continue
            inp_shape = shapes.get(inp, {})
            for mname, member in inp_shape.get("members", {}).items():
                traits = member.get("traits", {})
                tgt = shapes.get(member.get("target", ""), {}).get("traits", {})
                ln = {**tgt.get("smithy.api#length", {}), **traits.get("smithy.api#length", {})}
                row = {
                    "min_len": ln.get("min"),
                    "max_len": ln.get("max"),
                    "pattern": traits.get("smithy.api#pattern") or tgt.get("smithy.api#pattern"),
                    "service": sdk_id,
                    "go_package": go_pkg,
                    "model_file": fn,
                    "operation": shape_name(sid),
                    "member": mname,
                }
                if "smithy.api#idempotencyToken" in traits:
                    traited.append(row)
                elif TOKEN_NAME_RE.match(mname) and not is_read_only(shape):
                    untraited.append(row)
    provider_dir = next((a.split("=",1)[1] for a in sys.argv if a.startswith("--provider-dir=")), None)
    if provider_dir:
        mark_provider_usage(provider_dir, traited + untraited)
    for r in traited + untraited:
        r["go_field"] = go_field(r["member"])
        r["format"] = pick_format(r)
        r["name_is_token"] = bool(TOKEN_NAME_RE.match(r["member"]))
    out = {"traited": traited, "untraited": untraited}
    if "--go" in sys.argv:
        emit_go(traited, untraited)
        return
    if not md:
        json.dump(out, sys.stdout, indent=1)
        return

    def table(rows):
        by_svc = {}
        for r in rows:
            by_svc.setdefault((r["service"], r["go_package"]), []).append(r)
        lines = []
        for (svc, pkg), rs in sorted(by_svc.items()):
            lines.append(f"\n### {svc} (`service/{pkg}`)\n")
            lines.append("| Operation | Token member | Length | Called by upstream provider |")
            lines.append("|---|---|---|---|")
            for r in sorted(rs, key=lambda r: r["operation"]):
                l = f"{r['min_len'] or ''}..{r['max_len'] or ''}" if (r['min_len'] or r['max_len']) else ""
                used = {True: "yes", False: "", None: "?"}[r.get("used_by_provider")]
                lines.append(f"| `{r['operation']}` | `{r['member']}` | {l} | {used} |")
        return "\n".join(lines)

    n_svc = len({r["service"] for r in traited})
    used_t = [r for r in traited if r.get("used_by_provider")]
    used_u = [r for r in untraited if r.get("used_by_provider")]
    print("# Supported AWS APIs (idempotency-token operations)\n")
    print("Generated by `tools/gen-idempotent-ops/gen.py` from the Smithy models in")
    print("`aws/aws-sdk-go-v2/codegen/sdk-codegen/aws-models`. Do not edit by hand.\n")
    print(f"- Tier 1 (trait `smithy.api#idempotencyToken`): **{len(traited)} operations across {n_svc} services**.")
    print("  aws-sdk-go-v2 auto-fills these with a random UUID if left empty; our middleware")
    print("  sets a deterministic token first, so the SDK leaves it alone.")
    print(f"- Tier 2 (token-named member, no trait): **{len(untraited)} operations**.")
    print("  The SDK does not touch these; the provider must set them explicitly.")
    if used_t or used_u:
        print(f"- Called by upstream terraform-provider-aws today: **{len(used_t)} Tier 1** and **{len(used_u)} Tier 2** operations.")
        print("  These are the operations where the idempotent provider changes real apply behavior.")
    print("")
    if used_t or used_u:
        print("## Operations the provider calls today\n")
        print("### Tier 1 used by the provider\n")
        print(table(used_t))
        print("\n### Tier 2 used by the provider\n")
        print(table(used_u))
        print("")
    print("## Tier 1: operations with `smithy.api#idempotencyToken`\n")
    print(table(traited))
    print("\n\n## Tier 2: token-named members without the trait (manual)\n")
    print(table(untraited))

if __name__ == "__main__":
    main()
